config/routes.rb
Projectbook::Application.routes.draw do

  get "forum/dummy"

  resources :attachments

  get "services/contact"

  get "services/about_us"

  get "services/terms_of_use"

  get "services/privacy"
  
  get "services/faqs"

  get "user/profile"
  get "homepage/home"
 
  match 'projects/faculty/:faculty' => 'projects#index' 
  

  match "user" => "users#show", :as => 'user'
  match "service/faqs" => "services#faqs", :as => 'faqs'
  match "service/about_us" => "services#about_us", :as => 'about_us'
  match "service/privacy" => "services#privacy", :as => 'privacy'
  match "service/terms_of_use" => "services#terms_of_use", :as => 'terms_of_use'
  match "service/contact" => "services#contact", :as => 'contact'

  devise_for :users

  resources :users
  resources :faculties
  resources :projects do
    member do
      post 'follow'
      delete 'unfollow'
    end
	resources :attachments
  end

  root :to => 'homepage#home'

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :user, foreign_key: "user_id"
  belongs_to :project, foreign_key: "project_id"

  attr_accessor :file
  attr_accessible :user_id, :file, :project_id
  
  has_attached_file :file
  validates_attachment_size :file, :less_than => 50.megabytes
  validates_attachment_presence :file

end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_filter :set_attachment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    project = Project.find(params[:project_id])
    @attachments = project.attachments
    respond_with(@attachments)
  end

  def show
    project = Project.find(params[:project_id])
	@attachment = project.attachments.find(params[:id])
	    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @attachment }
    end
  end

  def new
    project = Project.find(params[:project_id])
	@attachment = project.attachments.build
	    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
  project = Project.find(params[:project_id])
  @attachment = project.attachment.find(params[:id])
  end

  def create
  
    project = Project.find(params[:project_id])
    @attachment = project.attachments.create(params[:attachment])
	
	  respond_to do |format|
      if @attachment.save
  
        format.html { redirect_to([@attachment.project, @attachment], :notice => 'Attachment was successfully created.') }

      else
        format.html { render :action => "new" }

      end
    end


  end

  def update

    project = Project.find(params[:project_id])

    @attachment = project.attachments.find(params[:id])

    respond_to do |format|
      if @attachment.update_attributes(params[:attachment])

        format.html { redirect_to([@attachment.project, @attachment], :notice => 'Attachment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @attachment.errors, :status => :unprocessable_entity }
      end
    end

  end

  def destroy
	project = Project.find(params[:project_id])
	@attachment = project.attachments.find(params[:id])
	@attachment.destroy

	    respond_to do |format|

      format.html { redirect_to(project_attachments_url) }
      format.xml  { head :ok }
	  end
  end

  private
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_form.html.erb
<%= form_for([@attachment.project,@attachment]) do |f| %>
  <% if @attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% @attachment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
  <%= f.label :File %><br />
  <%= f.file_field :file %>
  <br />
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<h1>Listing attachments</h1>



<table>
  <tr>
    <th><div class="col-md-8">File Name</p></div></th>
	
  </tr>

<% @attachments.each do |attachment| %>

  <tr>
	<td>
		<div class="col-md-8">
			<div class="attachment">
				<%= link_to attachment.file_file_name, attachment.file.url if attachment.file? %></p>
			</div>
		</div>
	</td>
	<% if user_signed_in? %>
	<td><div class="col-md-8"><%= link_to 'Delete',[attachment.project, attachment], method: :delete, data: { confirm: 'Are you sure?' } %></p></div></td>
	<% end %>
  </tr>


<% end %>
</table>

<br />

<% if user_signed_in? %>
	<div class="col-md-8">
		<div class="new-attachment">
			<%= link_to 'New Attachment', new_project_attachment_path %></p>
		</div>
	</div>
			
<% end %>

app/views/attachments/new.html.erb
<h1>New attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', project_attachments_path %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>



<%= link_to 'Back', project_attachments_path %>