config/routes.rb
Projectbook::Application.routes.draw do

  get "forum/dummy"

  resources :attachments

  get "services/contact"

  get "services/about_us"

  get "services/terms_of_use"

  get "services/privacy"
  
  get "services/faqs"

  get "user/profile"
  get "homepage/home"
 
  match 'projects/faculty/:faculty' => 'projects#index' 
  

  match "user" => "users#show", :as => 'user'
  match "service/faqs" => "services#faqs", :as => 'faqs'
  match "service/about_us" => "services#about_us", :as => 'about_us'
  match "service/privacy" => "services#privacy", :as => 'privacy'
  match "service/terms_of_use" => "services#terms_of_use", :as => 'terms_of_use'
  match "service/contact" => "services#contact", :as => 'contact'

  devise_for :users

  resources :users
  resources :faculties
  resources :projects do
    member do
      post 'follow'
      delete 'unfollow'
    end
	resources :attachments
  end

  root :to => 'homepage#home'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :faculty
  has_and_belongs_to_many :users
  has_many :milestones
  has_many :events
  has_and_belongs_to_many :companies
  has_and_belongs_to_many :searchcategories
  has_and_belongs_to_many :followers,
      class_name: "User",
      association_foreign_key: "user_id",
      join_table: "projects_followers"
    has_many :attachments

  
  attr_accessor :avatar
  attr_accessible :short_description, :name, :faculty_id, :avatar, :long_description
  
  has_attached_file :avatar, :styles => { :medium => "300x300#", :thumb => "100x100#", :rect => "500x250#" }, :default_url => "/images/:style/projectdefault.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_attachment_size :avatar, :less_than => 2.megabytes
  
  validates_presence_of :name, :short_description
  
  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/projects_controller.rb
# encoding: utf-8
class ProjectsController < ApplicationController    
  add_crumb "Projekte", :projects_path
  # GET /projects
  # GET /projects.json  
  def index  
    if params[:faculty] == ""
      redirect_to('/')
      return
    end
    
    @headingText = headingText
    searchtag = (params[:search])
    
    if params[:faculty] == "0" || params[:faculty] == nil
      if params[:search]		
        @projects = Project.find(:all, :conditions => 
			['name LIKE ? OR short_description LIKE ? OR long_description LIKE ?', "%#{searchtag}%", "%#{searchtag}%", "%#{searchtag}%"])  
      else
        @projects = Project.find(:all)
      end
    else
      if params[:search]
        @projects = Project.find_all_by_faculty_id(params[:faculty], 
          :conditions => ['name LIKE ? OR short_description LIKE ? OR long_description LIKE ?', "%#{searchtag}%", "%#{searchtag}%" , "%#{searchtag}%"])  
      else
        @projects = Project.find_all_by_faculty_id(params[:faculty])
      end
      add_crumb 'Fakultät '+ params[:faculty], '../../projects/faculty'+params[:faculty]
    end
      
    case params[:sort]      
      when "Erstellungsdatum"
        @projects.sort_by! {|u| u.created_at}
        @projects.reverse!  
      when "Aufrufe"
        @projects.sort_by! {|u| u.calls}   
        @projects.reverse!
      when "Follower"
        @projects.sort_by! {|u| u.followers.count}   
        @projects.reverse!    
      else 
        @projects.sort_by! {|u| u.name}
    end
          
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  def headingText
    if params[:search] != nil
      text = "Alle Suchergebnisse für '#{params[:search]}'"
    elsif params[:faculty] == "0" || params[:faculty] == nil
      text = 'Alle Projekte'
    else      
      text = "Projekte der Fakultät #{params[:faculty]} - #{Faculty.find_by_id(params[:faculty]).name}"
    end
    return text
  end

  def facultyBreadcrumb
    add_crumb 'Fakultät '+ @project.faculty_id.to_s, '../../projects/faculty/' + @project.faculty_id.to_s
  end
  
  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @project.calls = @project.calls + 1
    @project.save    
    facultyBreadcrumb()
    add_crumb @project.name, :project_path 
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new  
 
    add_crumb 'Neues Projekt', ''
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])    
    facultyBreadcrumb
    add_crumb @project.name, '../' + params[:id]    
    add_crumb 'Bearbeiten',  ''
   
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    @project.calls = 0
    @project.users << current_user    
    @project.save
    
    @users = @project.users
    @companies = @project.companies
    
    @teammembers = params[:teammember]
    @deleteteammembers = params[:deleteteammember]
    @sponsors = params[:sponsor]
    @deletesponsors = params[:deletesponsor]
    
    unless @teammembers.nil?
    @teammembers.each do |t|
    unless @users.exists?(t)
       @users << User.find(t)
      end
    end
    end
    
    unless @deleteteammembers.nil?
    @deleteteammembers.each do |t|
      if @users.exists?(t)
       @users.delete(User.find(t))
      end
    end
    end
    
    unless @sponsors.nil?
    @sponsors.each do |t|
    unless @companies.exists?(t)
       @companies << Company.find(t)
      end
    end
    end
    
    unless @deletesponsors.nil?
    @deletesponsors.each do |t|
    if @companies.exists?(t)
       @companies.delete(Company.find(t))
      end
    end
    end
    
    
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Projekt erfolgreich erstellt.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])
    @users = @project.users
    @companies = @project.companies
    @milestones = @project.milestones
    @events = @project.events

    @teammembers = params[:teammember]
    @deleteteammembers = params[:deleteteammember]
    @sponsors = params[:sponsor]
    @deletesponsors = params[:deletesponsor]
    @deletemilestones = params[:deletemilestone]
    @deleteevents = params[:deleteevent]
       
    unless @deletetemilestones.nil?        
      @deletemilestones.each do |t|        
         @milestones.delete(Milestone.find(t))   
      end
    end
    
    unless @deletetemilestones.nil?
    @deleteevents.each do |t|        
       @project.events.delete(Event.find(t))   
    end
    end
    
    unless @teammembers.nil?
    @teammembers.each do |t|
    unless @users.exists?(t)
       @users << User.find(t)
      end
    end
    end
    
    unless @deleteteammembers.nil?
    @deleteteammembers.each do |t|      
       @users.delete(User.find(t))      
    end
    end
    
    unless @sponsors.nil?
    @sponsors.each do |t|
    unless @companies.exists?(t)
       @companies << Company.find(t)
      end
    end
    end
    
    unless @deletesponsors.nil?
    @deletesponsors.each do |t|
    if @companies.exists?(t)
       @companies.delete(Company.find(t))
      end
    end
    end
         
    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Projekt erfolgreich geändert.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
  
  # POST /projects/1/follow
  # POST /projects/1/follow.json  
  def follow
    @project = Project.find(params[:id])
    @project.followers << current_user

    respond_to do |format|
      format.html { redirect_to @project, notice: 'Du folgst nun diesem Projekt.' }
      format.json { head :no_content }
    end
  end

  # DELETE /projects/1/unfollow
  # DELETE /projects/1/unfollow.json
  def unfollow
    @project = Project.find(params[:id])
    @project.followers.delete(current_user)

    respond_to do |format|
      format.html { redirect_to @project, notice: 'Du folgst diesem Projekt nicht mehr.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper  
end

app/views/projects/_detailsheader.html.erb
<div class="container-fluid">
  <div class="row project-header">
    <div class="col-md-6">
		<!--<%= link_to 'Projekte', projects_path, :class => "project-header__link" %>-->
		<h2 class="project-heading"><%= @project.name %></h2>
	</div>
	<div class="col-md-6">
	<%if user_signed_in?%>
		<%if @project.users.find_by_id(current_user.id) == current_user || development%>
		<div class="project-header__option">
			<%= link_to 'Datei',project_attachments_path(@project), :class => "project-header__link" %>
		</div>
		<%end%>
	<%end%>
		<div class="project-header__option">
			<%= link_to 'Übersicht', project_path(@project), :class => "project-header__link" %>
		</div>
		<!--development is set in helpers/application_helper.rb -->
		<%if user_signed_in?%>
		  	<%if @project.users.find_by_id(current_user.id) == current_user || development%>
				<div class="project-header__option">
					<%= link_to 'Projekt bearbeiten', edit_project_path(@project), :class => "project-header__link" %>
				</div>
	
				<div class="project-header__option">
					<%= link_to 'Projektforum', forum_dummy_path(:id => @project), :class => "project-header__link" %>
				</div>
				
			<%end%>
		<%end%>
	</div>
	
  </div>
</div>

app/views/projects/_form.html.erb
<%if user_signed_in?%>

<%= form_for(@project, :html => { :multipart => true }) do |f| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-container">
	<div class="edit-project__header">
		<h2 class="project-heading">Dein Projekt</h2>
	</div>
	<div class="edit-project__content">
			
		  <div class="field">
		    <p class="project-label"><%= f.label :name, 'Der Name' %></p><br/>
		    <%= f.text_field :name, :class =>"textfield" %>
		  </div>
		  
		  <div class="field">
		    <p class="project-label"><%= f.label :avatar, 'Das Projektbild' %></p><br/>
		    <%= f.file_field :avatar, :id => "filefield" %>
		  </div>
		  
		  <div class="field">
		    <p class="project-label"><%= f.label :faculty_id, 'Die Fakultaet' %></p><br/>
		    <%= f.select(:faculty_id, Faculty.all.collect {|faculty| [faculty.id]})%>
		  </div>
		  
		  <div class="field">
		    <p class="project-label"><%= f.label :short_description, 'Die Kurzbeschreibung (max 200 Zeichen)' %></p><br/>
		    <%= f.text_area :short_description, :onkeyup => "CheckMaxlength(this);", :maxlength => 200, :class => "textarea" %>
		  </div>
		  
		  <div class="field">
		    <p class="project-label"><%= f.label :long_description , 'Die lange Beschreibung' %></p><br/>
		    <%= f.text_area :long_description , :class => "textarea--long" %>
		  </div>
		  
		  <div class="field">
		  	<p class="project-label"><%= f.label 'Event hinzufügen' %></p><br/>
		    <button class="btn button" onclick="alert('Funktion im Prototyp nicht vorhanden!')">Event hinzufügen</button>

		  </div>
		  
		  <% unless @project.events.empty? %>
		  <div class="field">
		    <p class="project-label"><%= f.label 'Event löschen' %></p><br/>
			<% @project.events.each do |e| %> 
				<%= check_box_tag 'deleteevent[]', e.id -%>
				<%= e.name %>
				</br>
			<% end %>
		  </div>
		  <% end %>
		  
		  <div class="field">
		  	<p class="project-label"><%= f.label 'Meilenstein hinzufügen' %></p><br/>
		    <button class="btn button" onclick="alert('Funktion im Prototyp nicht vorhanden!')">Meilenstein hinzufügen </button>

		  </div>
		  
		  <% unless @project.milestones.empty? %>
		  <div class="field">
		    <p class="project-label"><%= f.label 'Meilenstein löschen' %></p><br/>
			<% @project.milestones.each do |m| %> 
				<%= check_box_tag 'deletemilestone[]', m.id -%>
				<%= m.name %>
				</br>
			<% end %>
		  </div>
		  <% end %>
		  
		  <div class="field">
		  	<p class="project-label"><%= f.label 'Sponsor hinzufügen' %></p><br/>
			<%= select_tag("sponsor[]", options_for_select((Company.all.map{|u| [ u.name, u.id ] } ) , params[:sponsors_id]),  :multiple => true, :size => 5  ) %> 
			</br>	  	
		  </div>
		  
		  <% unless @project.companies.empty? %>
		  <div class="field">
		  	<p class="project-label"><%= f.label 'Sponsor löschen' %></p><br/>
			<% @project.companies.each do |u| %> 
				<%= check_box_tag 'deletesponsor[]', u.id -%>
				<%= u.name %>
				<br/>
			<% end %>
		  </div>
		  <% end %>
		  	  		
		<div class="field">
			<p class="project-label"><%= f.label 'Teammitglied hinzufuegen' %></p><br/>
			<%= select_tag("teammember[]", options_for_select((User.all.map{|u| [ u.username, u.id ] } ), params[:users_id]),  :multiple => true, :size => 5  ) %> 		
		</div>
		
		<% unless @project.users.empty? %>
		<div class="field">
			<p class="project-label"><%= f.label 'Teammitglied löschen' %></p><br/>
			<% @project.users.each do |u| %> 
				<%= check_box_tag 'deleteteammember[]', u.id -%>
				<%= u.username %>
				<br/>
			<% end %>  
		</div>
		<% end %>
		
	</div>
  </div>  



  <div class="actions">
    <%= f.submit 'Projekt speichern', :class => "btn button button--submit" %>
  </div>
<% end %>

<%else%>
<p>Bitte zuerst anmelden!</p>
<%end%>

  <% if @project.users.first == current_user || development%>
	<%= button_to 'Löschen', @project, method: :delete, data: { confirm: 'Sind Sie sicher?' }, :class => "btn button button--submit", :style => "float:left"%>
<%end%>

app/views/projects/_projectsheader.html.erb
<% faculties = Faculty.all%>
<div class="newproject-filter-container">
	<div class="filter">
		<form action="/projects" method="get">		
    	<%= select_tag "faculty",  options_for_select([["Fakultät wählen", "0"]] +[["Alle Projekte" , "0"]] + faculties.collect{ |u| ["FK " + u.id.to_s + " - " + u.name, u.id] }, 
    	params[:faculty]),  
    	
    	class: 'form-control',    	
    	:onchange => "this.form.submit();" %>    	
	</form>	
	</div>
	<div class="newproject">
		<% if user_signed_in? %>
		  <%= button_to "Neues Projekt erstellen", new_project_path, :class => "btn button button--newproject", :method => :get %>
		<% end %>		
	</div>	
</div>

<!--<% faculties = Faculty.all%>
  	<div id="facultyselection">
  		Hier eine Fakul&aumlt ausw&aumlhlen:
  	<form action="/projects" method="get">		
    	<%= select_tag "faculty",  options_for_select([["Alle Projekte" , "0"]] + faculties.collect{ |u| ["FK " + u.id.to_s + " - " + u.name, u.id] }, 
    	params[:faculty]),  
    	:include_blank => true,
    	class: 'form-control',    	
    	:onchange => "this.form.submit();" %>    	
	</form>	
  	</div>
  	
  	<a class="btn btn-default"  href="../../projects/faculty/0" role="button">Alle Projekte</a>
  	
  	<% faculties.each do |faculty| %>	
		<a class="btn btn-default"  href="../../projects/faculty/<%= faculty.id %>" role="button"><%= faculty.id %> <%=faculty.name %></a>
	<%end%> -->
	
	<!--<div id="search">
		
		<% if params[:faculty] == nil %>
			<% faculty = 0 %>
		<% else %>
			<% faculty = params[:faculty] %>
		<% end %>
		
		<form action="/projects/faculty/<%= faculty %>" method="get">
			<%= text_field_tag :search, params[:search] %>
	    	<%= submit_tag "Suche", :name => nil %>
	    </form>
	</div>-->

app/views/projects/edit.html.erb
<%=render "detailsheader"%>

<%= render 'form' %>

<!--  
<%= link_to 'Anzeigen', @project %> |
<%= link_to 'Zurück', projects_path %>
-->

app/views/projects/index.html.erb
<%if user_signed_in?%>

<% faculties = Faculty.all%>
<%=render 'projectsheader'%>

<div class="filter-header">
	<h2 class="project-heading"><%=@headingText%></h2>
</div>

<%if @projects.count == 0%>
	<%if params[:search] != nil%>
		<h3>Ihre Suche ergab leider keine Treffer.</h3>
	<%else%>
		<h3>Derzeit ist kein Projekt in dieser Kategorie vorhanden.</h3>
	<%end%>	
<%else%>
<div class="sortby">
	<form action="/projects/faculty/<%=params[:faculty]%> " method="get">
    	<%= select_tag "sort", options_for_select(["Sortieren nach", "Name", "Aufrufe", "Follower", "Erstellungsdatum"], params[:sort]),    
    	#class: 'form-control',
    	:onchange => "this.form.submit();" %>    	
	</form>	
</div>
<%end%>


<% @projects.each do |project| %>
    <a href="<%= url_for(project) %>">
	  <div class="panel panel-default">
		<div class="panel-heading">
		  <%= project.name %>
		</div>
		<div class="panel-body">
		  <div class="row">
		    <div class="col-xs-2">
			  <%= image_tag(project.avatar.url(:medium), class: "img-responsive") %>
			</div>
			<div class="col-xs-6">
			  <p><%= project.short_description %></p>
			  <br />
			  <div class="row text-center">
			    <div class="col-xs-4">
			      <strong><%= project.followers.count %></strong>
				  <br />
				  <%= "follower".pluralize(project.followers.count) %>
				</div>
				<div class="col-xs-4">
				  <strong><%= project.calls %></strong><br>
				  <%= "view".pluralize(project.followers.count) %>
				</div>
				<div class="col-xs-4">
				  <strong><%= project.created_at.strftime("%d.%m.%Y") %></strong>
				  <br>
				  gestartet
				</div>
		      </div>
		    </div>
			<div class="col-xs-4">
			  Derzeit suchen wir:<br /><br />
			  <% project.searchcategories.each do |s| %> 
				<div class="searchcategory homesearchcategory">
				  <p><%= s.name %></p>
				</div>
			  <% end %>
			</div>						
	      </div>
		</div>
	  </div>
	</a>
<% end %>

<%else%>
<p>Bitte zuerst anmelden!</p>
<%end%>
<FORM><INPUT Type="button" VALUE="Zurück" onClick="history.go(-1);return true;"></FORM>

app/views/projects/new.html.erb
<%= render 'form' %>

<%= link_to 'Zurück', projects_path %>

app/views/projects/show.html.erb
<%=render "detailsheader"%>


<div class="project-content">
	<% if !@project.avatar_file_name.nil? %>
	<div class="project-img-container">
		<%= image_tag @project.avatar.url(:rect), :class => "img--project" %>
	</div>
	<% else %>
	<div class="project-img-container--no-image"></div>
	<%end%>
	<div class ="social-container">
	<div class="row">
	<div class="col-md-6">
		<strong><%= @project.followers.count %></strong> <%= "Follower".pluralize(@project.followers.count) %>
		<% if @project.followers.include?(current_user) %>
			<%= form_tag(unfollow_project_path, method: "delete") do %>
				<button type="submit" class="btn btn-danger"<%if !user_signed_in?%>disabled="disabled"<%end%>>Nicht mehr folgen</button>
			<% end %>
		<% else %> 
			<%= form_tag(follow_project_path, method: "post") do %>
				<button type="submit" class="btn btn-success"<%if !user_signed_in?%>disabled="disabled"<%end%> >Folgen</button>
			<% end %>
		<% end %>
	</div>
	
	<div class="col-md-6, project-social">
	<h5>Teile dieses Projekt</h5>
	<a href="http://www.facebook.de"><i id="social" class="fa fa-facebook-square fa-3x social-fb"></i></a>
    <a href="http://www.twitter.de"><i id="social" class="fa fa-twitter-square fa-3x social-tw"></i></a>
    <a href="https://plus.google.com/"><i id="social" class="fa fa-google-plus-square fa-3x social-gp"></i></a>
</div>
</div>

</div>	
	<div class="project-information">
		<% if @project.events.exists? %>
		<div class="project-information__documents">
			<div class="project-information__documentlist">
				<% @project.events.each do |u| %> 
					<div class="project-information__teamlist__teammember">
						<div class="teammember-information">
							<p><%= u.name %></p>
						</div>
					</div>
				<% end %>
			</div>
		</div>
		<% end %>
		
		<div class="project-information__main">
			<% if @project.long_description.blank? %>
				<p class="project-description"><%= @project.short_description %></p>
			
			<% else %>
				<p class="project-description"><%= @project.long_description %></p>
			<% end %>
			<% if @project.companies.exists? %>
			<p class="subheader">Die Sponsoren</p>
			<div class="sponsor-container">
				<% @project.companies.each do |u| %> 
					<div class="sponsor">
						<p><%= u.name %></p>
					</div>
				<% end %>
			</div>
			<% end %>
			<% if @project.searchcategories.exists? %>
			<p class="subheader">Wir suchen</p>
			<div class="searchcategory-container">
				<% @project.searchcategories.each do |s| %> 
					<div class="searchcategory detailsearchcategory">
						<p><%= s.name %></p>
					</div>
				<% end %>
			</div>
			<% end %>
			<% if @project.milestones.exists? %>
			<p class="subheader">Die Meilensteine</p>
			<div class="milestone-container">
				<% @project.milestones.each do |m| %> 
					<div class="milestone">
						<div class="milestone__square-container">
							<div class="milestone__square"></div>
						</div>	
						<div class="milestone__information">
							<p><strong><%= m.name %> vom <%= m.date.strftime("%d.%m.%Y") %></strong></p>
							<p><%= m.description %></p>
						</div>
					</div>
				<% end %>
			</div>
			<% end %>
		</div>
		<% if @project.users.exists? %>
		<div class="project-information__team">
			<div class="project-information__teamlist">
				<% @project.users.each do |u| %> 
					<div class="project-information__teamlist__teammember">
						<%= image_tag u.avatar.url(:thumb), :class => "img--teammember" %>
						<div class="teammember-information">
							<p><%= u.firstname %></p>
							<p><%= u.surname %></p>
							<p><%= u.username %></p>
							<p><%= u.email %></p>	
							<% if u.id == @project.users.first.id %>
							<p> Projektverantwortlicher </p>
							<% end %>
						</div>
					</div>
				<% end %>
			</div>
		</div>
		<% end %>
	</div>
</div>

<br/>
<% if false %>

  <b>Faculty:</b>
  <%= @project.faculty_id %> <%= Faculty.find_by_id(@project.faculty_id).name %>


<!-- Diese Abfrage kann entfernt werden sobald die Beispiel
	Projekte alle einen Ersteller/Mitglied haben!!!-->
<%if @project.users.count > 0 %>
<p>	<b> Projektverantwortlicher: </b>
	<%= @project.users.first.username%>
</p>
<%end%>



<p><b> Meilensteine: </b><br />

<!--<% @project.milestones.each do |m| %> 
	Meilenstein <%= m.id %> - <%= m.name %> vom <%= m.date %><br />
	Beschreibung:<br />
	<%= m.description %>
	<br />
	<br />
<% end %>-->

<FORM><INPUT Type="button" VALUE="Zurück" onClick="history.go(-1);return true;"></FORM>
	<% end %>
</div>