config/routes.rb
Projectbook::Application.routes.draw do

  get "forum/dummy"

  resources :attachments

  get "services/contact"

  get "services/about_us"

  get "services/terms_of_use"

  get "services/privacy"
  
  get "services/faqs"

  get "user/profile"
  get "homepage/home"
 
  match 'projects/faculty/:faculty' => 'projects#index' 
  

  match "user" => "users#show", :as => 'user'
  match "service/faqs" => "services#faqs", :as => 'faqs'
  match "service/about_us" => "services#about_us", :as => 'about_us'
  match "service/privacy" => "services#privacy", :as => 'privacy'
  match "service/terms_of_use" => "services#terms_of_use", :as => 'terms_of_use'
  match "service/contact" => "services#contact", :as => 'contact'

  devise_for :users

  resources :users
  resources :faculties
  resources :projects do
    member do
      post 'follow'
      delete 'unfollow'
    end
	resources :attachments
  end

  root :to => 'homepage#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>INCEPTA</title> 
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
</head>
<body>

<div id="topnav" class="navbar navbar-inverse navbar-default navbar-static-top header-position" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to 'INCEPTA', main_app.root_path, :class => 'navbar-brand project-link'%>
        </div>
        <div class="col-sx-4 col-sm-6 pull-left">
	        <%= form_tag projects_path, :method => 'get', :id => 'search-mini-form', 
	        	:class => 'navbar-form', :role => 'search' do -%>
                <div class="form-group">
                	<% if user_signed_in? %>
                    	<div id="search" class="input-group input-group-sm">	        
							<%= text_field_tag :search, params[:search], 
								:class => 'search-query form-control col-sm-5', :placeholder => 'Suche...' %>
							<span class="input-group-btn">
								<button type="submit" id="search" class="btn btn-default">
                           			<i class="fa fa-search"></i>
                           		</button>
                           	</span>
                    	</div>
                    <% end %>
                </div>
			<% end -%>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Startseite", main_app.root_path %></li>
                <% if user_signed_in? %>
                  <li class="dropdown">
                      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                          <%= current_user.username %>
                          <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu">
                          <li><%= link_to raw('<i class="fa fa-user"></i> Mein Profil'), user_path %></li>
                          <li><%= link_to raw('<i class="fa fa-sign-out"></i> Ausloggen'), main_app.destroy_user_session_path, :method => :delete %></li>
                      </ul>
                  </li>
                <% else %>
                  <li><%= link_to 'Registrieren', main_app.new_user_registration_path %></li>
                  <li><%= link_to "Log in", main_app.new_user_session_path %></li>
                <% end %>
            </ul>
        </div>
        <!--/.nav-collapse -->        
    </div>
</div>
<div class="breadcrumb">
	Sie sind hier: <%= render_crumbs last_crumb_linked: false %>
</div>

<div class="container page-wrap">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>

    <%= yield %>
</div>



<footer id="footer" class="navbar navbar-default navbar-inverse">
    <div class="container-fluid text-center">
        <p class="navbar-text">&copy; 2015 INCEPTA</p>
        <ul class="nav navbar-nav pull-right">
            <li><%= link_to 'Kontakt', contact_path %></li>
            <li><%= link_to 'Datenschutz', privacy_path %></li>
            <li><%= link_to 'Nutzungsbedingungen', terms_of_use_path %></li>
            <li><%= link_to 'Über uns', about_us_path %></li>
            <li><%= link_to 'FAQs', faqs_path %></li>
        </ul>
    </div>
</footer>
</body>
</html>